# Generated by Django 3.2.8 on 2021-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='message',
            field=models.CharField(default='my message', max_length=60),
            preserve_default=False,
        ),
    ]
