# Generated by Django 3.2.8 on 2021-10-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campaign_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='text_color',
            field=models.CharField(default='#000000', max_length=60),
            preserve_default=False,
        ),
    ]
