# Generated by Django 3.2.8 on 2021-10-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211025_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
