# Generated by Django 3.2.8 on 2021-10-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211026_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
