# Generated by Django 3.2.8 on 2021-10-26 07:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_steps_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='token',
            field=models.CharField(default=api.models.RandomID, editable=False, max_length=6, unique=True),
        ),
    ]
