# Generated by Django 3.2.8 on 2021-10-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_campaign_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parrain',
            unique_together={('campaign', 'email')},
        ),
    ]
