# Generated by Django 3.2.8 on 2021-10-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_parrain_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='steps',
            unique_together={('campaign', 'order')},
        ),
    ]
