# Generated by Django 3.2.8 on 2021-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211026_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='site',
            field=models.CharField(default='joyger.fr', max_length=200),
            preserve_default=False,
        ),
    ]
