# Generated by Django 3.2.8 on 2021-10-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_campaign_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='site',
        ),
    ]
