# Generated by Django 3.2.8 on 2021-10-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_campaign_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='web_site',
            field=models.CharField(default='joyger.fr', max_length=200),
            preserve_default=False,
        ),
    ]
